name: mask_recommender
channels:
  - conda-forge
dependencies:
  - arviz
  - autopep8
  - beautifulsoup4
  - boto3
  - dask
  - hdbscan
  - jax
  - jaxlib=0.6.2
  - jupyter
  - jupyterlab=4.4.1
  - moto
  - matplotlib
  - numpy
  - numpyro
  - pytorch
  - opencv
  - openpyxl
  - pandas
  - pre_commit
  - protobuf
  - psycopg2
  - pytest
  - pymc
  - python=3.11
  - scikit-learn
  - seaborn
  - pip
  - pip:
    - mediapipe
    - levenshtein
    - graphica
  - selenium
  - tqdm
